CREATE TABLE IF NOT EXISTS `marks` (
  `id` int(11) NOT NULL,
  `profile id` int(11) NOT NULL,
  `student id` varchar(100) NOT NULL,
  `course work 1` float NOT NULL DEFAULT '0',
  `course work 2` float NOT NULL DEFAULT '0',
  `course work 3` float NOT NULL DEFAULT '0',
  `course work 4` float NOT NULL DEFAULT '0',
  `course work 5` float NOT NULL DEFAULT '0',
  `course work 6` float NOT NULL DEFAULT '0',
  `course work 7` float NOT NULL DEFAULT '0',
  `course work 8` float NOT NULL DEFAULT '0',
  `course work 9` float NOT NULL DEFAULT '0',
  `course work 10` float NOT NULL DEFAULT '0',
  `course work percentage` float NOT NULL,
  `final weight percentage` float NOT NULL,
  `final exam` float NOT NULL,
  `weighted course work` float NOT NULL,
  `weighted final mark` float NOT NULL,
  `combined mark` int(11) NOT NULL,
  `grade` varchar(100) NOT NULL,
  `deleted` enum('TRUE','FALSE') NOT NULL DEFAULT 'FALSE',
  `comment` text NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 COMMENT='This table contains the marks of the students';
