
INSERT IGNORE INTO `subjects` (`id`, `title`, `pry level`, `o level`, `a level`, `school`) VALUES
  (1, 'PRINCIPLES OF ACCOUNTS', '', '', '', 0),
  (2, 'AGRICULTURE', '', '', '', 0),
  (3, 'ART', '', '', '', 0),
  (4, 'BIOLOGY', '', '', '', 0),
  (5, 'BUSINESS STUDIES', '', '', '', 0),
  (6, 'COMMERCE', '', '', '', 0),
  (7, 'TONGA', '', '', '', 0),
  (8, 'ENGLISH', '', '', '', 0),
  (9, 'FRENCH', '', '', '', 0),
  (10, 'GEOGRAPHY', '', '', '', 0),
  (11, 'HISTORY', '', '', '', 0),
  (12, 'INTERGRATED SCIENCE', '', '', '', 0),
  (13, 'ENGLISH LITERATURE', '', '', '', 0),
  (14, 'MATHEMATICS', '', '', '', 0),
  (15, 'METALWORK', '', '', '', 0),
  (16, 'MUSIC', '', '', '', 0),
  (17, 'NDAU', '', '', '', 0),
  (18, 'NDEBELE', '', '', '', 0),
  (19, 'PHYSICAL EDUCATION AND SPORT', '', '', '', 0),
  (20, 'PHYSICAL SCIENCE', '', '', '', 0),
  (21, 'PORTUGUESE', '', '', '', 0),
  (22, 'RELIGIOUS STUDIES', '', '', '', 0),
  (23, 'SHONA', '', '', '', 0),
  (25, 'VENDA', '', '', '', 0),
  (26, 'WOODWORK', '', '', '', 0),
  (27, 'HUMAN AND SOCIAL BIOLOGY', '', '', '', 0),
  (28, 'SOCIOLOGY', '', '', '', 0),
  (29, 'STATISTICS', '', '', '', 0),
  (30, 'TECHNICAL GRAPHICS', '', '', '', 0),
  (32, 'CHEMISTRY', '', '', '', 0),
  (33, 'HOME ECONOMICS', '', '', '', 0),
  (34, 'FASHION AND FABRICS', '', '', '', 0),
  (35, 'FOOD AND NUTRITION', '', '', '', 0),
  (36, 'HOME MANAGEMENT', '', '', '', 0),
  (38, 'ECONOMICS', '', '', '', 0),
  (39, 'COMPUTER STUDIES', '', '', '', 0),
  (43, 'LAW', '', '', '', 0),
  (44, 'FURTHER MATHEMATICS', '', '', '', 0),
  (45, 'GEOMETRICAL & MECHANICAL/BUILDING DRAWING', '', '', '', 0),
  (46, 'LITERATURE IN ENGLISH', '', '', '', 0),
  (47, 'DIVINITY', '', '', '', 0),
  (48, 'ENGLISH LANGUAGE AND COMMUNICATION SKILLS ', '', '', '', 0),
  (49, 'TEXTILES AND CLOTHING DESIGN', '', '', '', 0),
  (50, 'FOOD SCIENCE', '', '', '', 0);
